baseURL: https://lampsfolio.pages.dev/
languageCode: en-us
build:
  writeStats: true
params:
  title: LampsFolio
  author: Bruno Lamps
  description: Portfolio site of Bruno Lamps
  copyright: >-
    powered by [hugo](https://gohugo.io/), [aafu theme](https://themes.gohugo.io/themes/aafu/) & [Cloudflare](https://www.cloudflare.com/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Bruno 'Lamps' Menezes"
    tagline: Software Developer
    location: "Aracaju. Brazil"
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/bsmenezes88/"
        title: LinkedIn
      - icon: fab fa-stack-overflow
        url: "https://stackoverflow.com/users/2600554/bruno-lamps"
        title: StackOverflow
      - icon: fab fa-github
        url: "https://github.com/lampsbr"
        title: GitHub
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: publication
    - item: project
    #- item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: I'm a software developer! I love to be learning new stuff and to work in teams, even if sometimes the only available team is github copilot. 
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Software Engineer
        dates: 2017 - *Present*
        company: Audit Office of Sergipe
        url: "https://www.tce.se.gov.br/"
        details: |1-
          - Tech Lead for development and maintenance of a govt web portal
          - Modular application with dozen different technologies
          - Vue.js, Bootstrap, .NET, SQL Server, Java, Elastic, Hangfire etc
      - position: Software Engineer
        dates: 2015 - 2017
        company: Water Company of Sergipe
        url: "https://www.deso-se.com.br/"
      - position: Network Analyst
        dates: 2015
        url: "https://emgetis.se.gov.br/"
        company: Emgetis
      - position: Java Developer
        dates: 2014
        url: "https://ufs.br/"
        company: UFS
      - position: Java Developer
        dates: 2012 - 2013
        url: "https://www.aracaju.se.gov.br/"
        company: City's Health Department
      - position: Retail IT analyst
        dates: 2010 - 2011
        url: "https://www.pisolar.com.br/"
        company: Pisolar
      - position: Intern web developer
        dates: 2009
        url: "https://www.linkedin.com/company/lbs-local/?originalSubdomain=br"
        company: LBS Local
      - position: Intern
        dates: 2008
        url: "https://www.userede.com.br/"
        company: Rede
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: Bachelor of Technology
        college: Mackenzie Presbiterian University
        dates: 2006 - 2009
      - degree: Bachelor of Economics
        college: Cesumar University
        dates: 2020 - 2023
  publication:
    title: Courses
    icon: fas fa-book
    format:
      - date
      - title
      - authors
    types:
      - Udemy
      - Alura
    list:
      - title: >-
          Vue.js 2
        date: "2019"
        type: Alura
      - title: >-
          Express.js
        date: "2018"
        type: Alura
      - title: Docker
        date: "2017"
        type: Alura
      - title: >-
          Flutter & Dart - The Complete Guide
        date: "2023"
        url: "https://www.udemy.com/course/learn-flutter-dart-to-build-ios-android-apps"
        authors: Maximilian Schwarzmüller
        type: Udemy
      - title: >-
          React 18 Tutorial and Projects Course
        date: "2021"
        url: "https://www.udemy.com/course/react-tutorial-and-projects-course"
        authors: John Smilga
        type: Udemy
      - title: >-
          NestJS - From Zero to Hero
        date: "2019"
        url: "https://www.udemy.com/course/nestjs-zero-to-hero"
        authors: Ariel Weinberger
        type: Udemy
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: This Portfolio (2024)
        url: "#"
        description: Crafted in few hours using Hugo and aafu theme. First experience with all technologies, including Go and Cloudflare. 
      - title: Portal do Jurisdicionado (2017 -)
        url: "https://www.tcese.tc.br/sagres-producao/login.xhtml"
        description: Government web portal designed to aid communications and workflow between local audit office and mayors, legislators, laywers, accounting offices etc
      - title: NDA warehouse system (2023)
        url: "#"
        description: Web application to manage ecommerce-related warehouse operations. Features barcode scanning, in-browser OCR, audio capacities etc
      - title: Torliga (2022 - 2023)
        url: "https://torliga.com"
        description: Promotions and gaming platform. Integrated with telecom APIs, antifraud systems, football APIs. Project built from scratch using NestJS, VueJS, Postgres, Redis, Bull among other technologies
      - title: NDA startup social network (2021)
        url: "#"
        description: Wrote a ton of features for a retired social network startup. Features included chat, admin portal, signup process, feed, groups etc. Tech stack included cloud providers, NestJS, React, NextJS, Lightning, Bootstrap, Helmet, Fastify, GraphQL among others
      - title: Poop quality tracker (2020 / hobby)
        url: "https://msltracker.web.app"
        description: WebApp written using Vue.JS 2, bootstrap-vue and firebase. Features social login, only one useful feature and that Json database they love. I started rewritting it, hope to finish it before Stallman's GNU OS
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: "Skill 1, Skill 2"
        skillrating: 90
      - skill: Skill 3
        skillrating: 80
      - skill: Skill 4
        skillrating: 50
  hobby:
    title: Hobbies
    icon: fas fa-gamepad
    list:
      - hobby: Watching esports
      - hobby: Running
      - Hobby: Swimming
      - hobby: Cooking salad
      - hobby: Mobile gaming
      - hobby: Music (if too loud)
